# Generated by Django 4.1.1 on 2022-09-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('stars', models.PositiveIntegerField(default=1)),
                ('fit_type', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('colors', models.CharField(max_length=100)),
                ('sizes', models.CharField(max_length=50)),
                ('features', models.TextField()),
                ('stock', models.IntegerField()),
                ('img', models.ImageField(upload_to='store/product_images')),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
