# Generated by Django 4.1.1 on 2022-09-25 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_productimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
