# Generated by Django 4.1.1 on 2022-10-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
