# Generated by Django 4.1.1 on 2022-10-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('json_field', models.CharField(max_length=99999)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zip', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.CharField(max_length=10)),
                ('payment', models.CharField(max_length=10)),
            ],
        ),
    ]
