# Generated by Django 4.1.1 on 2022-10-10 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(choices=[(1, 'Order Placed'), (2, 'Shipped to warehouse'), (3, 'Packaging complete'), (4, 'Arrived to your country'), (5, 'Delivered!')], default=1)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.order')),
            ],
        ),
    ]
