# Generated by Django 4.1.1 on 2022-10-10 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_order_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
