# Generated by Django 4.1.1 on 2022-10-10 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Store', '0013_remove_orderupdate_order_delete_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('json_field', models.CharField(max_length=99999)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zip', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.CharField(max_length=10)),
                ('payment', models.CharField(max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(choices=[(1, 'Order Placed'), (2, 'Shipped to warehouse'), (3, 'Packaging complete'), (4, 'Arrived to your country'), (5, 'Delivered!')], default=1)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.order')),
            ],
        ),
    ]
