# Generated by Django 4.1.1 on 2022-10-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0016_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
